from transformers import pipeline

prompt = "List of questions to ask someone:\n1."
total_num_questions = 500000

def process_questions(batch):
    # TODO: process the text generated by the model
    pass

def generate_test_cases(prompt, model_name=None):
    if model_name:
        generator = pipeline('text-generation', model=model_name, max_length=150)
    else:
        generator = pipeline('text-generation', max_length=150)

    num_questions = 0
    questions = []
    while num_questions < total_num_questions:
        text = generator(prompt)
        new_questions = process_questions(text)
        questions += new_questions

    return questions
